version: "3.9"

services:
    apache:
        image: httpd:latest
        container_name: frontend
        ports:
            - 8080:80
        volumes:
            - .:/usr/local/apache2/htdocs
            - /usr/local/apache2/htdocs/node_modules
