version: "3"

services:
    frontend:
        image: webpack
        container_name: frontend
        build: .
        ports:
            - 8080:8080
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
volumes:
    node_modules: